.\" Pipe this output to groff -man -Tutf8 | less
.\"
.TH "BROZIP" 1 "" "Brozip 1.0" "Brozip Manual"
.\" Disable hyphenantion and ragged-right
.nh
.ad l
.SH NAME
.P
brozip \- concurrently compress, decompress files using the Brotli algorithm
.SH SYNOPSIS
.P
\fBbrozip\fR [\fIOPTION\fR]... [\fIARG\fR]...
.SH DESCRIPTION
.P
The \fBbrozip\fR program compresses and decompresses files using Google's Brotli algorithm. If no files are specified, \fBbrozip\fR will compress from standard input, or decompress to standard ouput. When in compression mode, each file will be replaced with another file with the suffix, set by the \fB\-S\fR suffix option, added, if possible
.P
In decompression mode, each file will be checked for existence, as will the file with the suffix added
.P
\fBbrozip\fR exposes compression options and defaults to values used by Google
.SH OPTIONS
.TP 4
\fB\-b\fR \fIVAL\fR, \fB\-\-lgblock\fR=\fIVAL\fR (absent=0)
Base 2 logarithm of the maximum input block size. Range is 16 to 24. If set to 0, the value will be set based on the quality. 
.TP 4
\fB\-c\fR, \fB\-\-compress\fR
compress files, if flag not given then \fBbrozip\fR will decompress files 
.TP 4
\fB\-d\fR \fIVAL\fR, \fB\-\-directory\fR=\fIVAL\fR (absent=.)
What directory to output files to, defaults to this current directory
.TP 4
\fB\-\-help\fR[=\fIFMT\fR] (default=pager)
Show this help in format \fIFMT\fR (pager, plain or groff).
.TP 4
\fB\-m\fR \fIVAL\fR, \fB\-\-mode\fR=\fIVAL\fR (absent=generic)
Mode to use. Can be \fBgeneric\fR, \fBtext\fR assuming UTF\-8, or \fBfont\fR assuming WOFF 2.0
.TP 4
\fB\-q\fR \fIVAL\fR, \fB\-\-quality\fR=\fIVAL\fR (absent=11)
Controls the compression\-speed vs compression\-density tradeoffs. The higher the quality, the slower the compression. Range is 0 to 11.
.TP 4
\fB\-r\fR, \fB\-\-recursive\fR
This option is used to \fBbrozip\fR the files in a directory tree
.TP 4
\fB\-s\fR, \fB\-\-serial\fR
Turn off concurrency, do work serially
.TP 4
\fB\-S\fR \fIVAL\fR, \fB\-\-suffix\fR=\fIVAL\fR (absent=bro)
What suffix to use on outputted files
.TP 4
\fB\-\-version\fR
Show version information.
.TP 4
\fB\-w\fR \fIVAL\fR, \fB\-\-lgwin\fR=\fIVAL\fR (absent=22)
Base 2 logarithm of the sliding window size. Range is 10 to 24.
.SH AUTHOR
.P
brozip was written by Edgar Aroutiounian
.SH BUGS
.P
See development at http://github.com/fxfactorial/brozip and file bug reports there.
.SH MISC
.P
brozip is written in OCaml with bindings to Google's Brotli C/C++ library. Those bindings are available here: http://github.com/fxfactorial/ocaml\-brotli